// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using social_media_console_app.Data;

#nullable disable

namespace social_media_console_app.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260516213405_IdkAnymoreMigration")]
    partial class IdkAnymoreMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("social_media_console_app.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentContent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CommenterUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommenterUserId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentContent = "Nice post!",
                            CommenterUserId = 2,
                            CreatedAt = new DateTime(2026, 5, 14, 18, 42, 34, 0, DateTimeKind.Utc),
                            PostId = 1
                        });
                });

            modelBuilder.Entity("social_media_console_app.Models.Friendship", b =>
                {
                    b.Property<int>("RequesterUserId")
                        .HasColumnType("int");

                    b.Property<int>("AddresseeUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FriendshipStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("RequesterUserId", "AddresseeUserId");

                    b.HasIndex("AddresseeUserId");

                    b.ToTable("Friendships", (string)null);

                    b.HasData(
                        new
                        {
                            RequesterUserId = 2,
                            AddresseeUserId = 1,
                            CreatedAt = new DateTime(2026, 5, 14, 18, 43, 58, 0, DateTimeKind.Utc),
                            FriendshipStatus = "Accepted"
                        });
                });

            modelBuilder.Entity("social_media_console_app.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ReceiverUserId")
                        .HasColumnType("int");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverUserId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("Messages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 14, 18, 47, 58, 0, DateTimeKind.Utc),
                            IsRead = false,
                            MessageContent = "Hello first admin! i am the second admin",
                            ReceiverUserId = 1,
                            SenderUserId = 2
                        });
                });

            modelBuilder.Entity("social_media_console_app.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostContent")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("PostTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 14, 18, 30, 58, 0, DateTimeKind.Utc),
                            PostContent = "this is initial admin post",
                            PostTitle = "Initial admin post",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("social_media_console_app.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("nchar(44)")
                        .IsFixedLength();

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("nchar(44)")
                        .IsFixedLength();

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_User_DateOfBirth", "DATEDIFF(year, DateOfBirth, GETUTCDATE()) BETWEEN 13 AND 100");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "I am admin of this app",
                            CreatedAt = new DateTime(2026, 5, 14, 18, 29, 30, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2000, 4, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin123@gmail.com",
                            PasswordHash = "ncE/vkagQZft0U5DxV0Z4IbHNBWgVkt/1RC/haf3nPg=",
                            PasswordSalt = "oNsJmAzkVehBjvRvQta4DtP3DveFpzniZ50nST4F2Pg=",
                            Username = "first_admin"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "I am the second admin of this app",
                            CreatedAt = new DateTime(2026, 5, 14, 18, 40, 30, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2005, 12, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "secondadmin123@gmail.com",
                            PasswordHash = "ncE/vkagQZft0U5DxV0Z4IbHNBWgVkt/1RC/haf3nPg=",
                            PasswordSalt = "oNsJmAzkVehBjvRvQta4DtP3DveFpzniZ50nST4F2Pg=",
                            Username = "second_admin"
                        });
                });

            modelBuilder.Entity("social_media_console_app.Models.Comment", b =>
                {
                    b.HasOne("social_media_console_app.Models.User", "CommenterUser")
                        .WithMany("Comments")
                        .HasForeignKey("CommenterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("social_media_console_app.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommenterUser");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("social_media_console_app.Models.Friendship", b =>
                {
                    b.HasOne("social_media_console_app.Models.User", "AddresseeUser")
                        .WithMany("ReceivedFriendRequests")
                        .HasForeignKey("AddresseeUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("social_media_console_app.Models.User", "RequesterUser")
                        .WithMany("SentFriendRequests")
                        .HasForeignKey("RequesterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AddresseeUser");

                    b.Navigation("RequesterUser");
                });

            modelBuilder.Entity("social_media_console_app.Models.Message", b =>
                {
                    b.HasOne("social_media_console_app.Models.User", "ReceiverUser")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceiverUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("social_media_console_app.Models.User", "SenderUser")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReceiverUser");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("social_media_console_app.Models.Post", b =>
                {
                    b.HasOne("social_media_console_app.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("social_media_console_app.Models.Post", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("social_media_console_app.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Posts");

                    b.Navigation("ReceivedFriendRequests");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentFriendRequests");

                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
